version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: crown-crm-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: crown_crm
    volumes:
      - crown_pg_data:/var/lib/postgresql/data

volumes:
  crown_pg_data:
